# Generated by Django 5.1.4 on 2025-03-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookshelf_category'),
        ('users', '0003_completedbook_readingchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingchallenge',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
