# Generated by Django 5.1.4 on 2025-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookshelf_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='category',
            field=models.CharField(choices=[('favorites', 'Favorites'), ('watchlist', 'Watchlist')], default='to_read', max_length=20),
        ),
    ]
