# Generated by Django 5.1.4 on 2025-03-20 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_favorites_book_google_book_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='category',
            field=models.CharField(choices=[('favorites', 'Favorites'), ('watchlist', 'Watchlist'), ('to_read', 'To Read')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelves', to=settings.AUTH_USER_MODEL),
        ),
    ]
