# Generated by Django 5.1.4 on 2025-03-29 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookshelf_unique_together_bookshelf_added_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookshelf',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='category',
            field=models.CharField(choices=[('reading', 'Currently Reading'), ('completed', 'Completed'), ('wishlist', 'Wishlist'), ('favorite', 'Favorite'), ('to-read', 'To Read')], default='wishlist', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='bookshelf',
            constraint=models.UniqueConstraint(fields=('user', 'google_book_id'), name='unique_user_google_book'),
        ),
        migrations.AddConstraint(
            model_name='bookshelf',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_local_book'),
        ),
    ]
