# Generated by Django 5.1.4 on 2025-04-10 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookshelf_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_book_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.URLField(blank=True)),
                ('list_type', models.CharField(choices=[('favourite', 'Favourite'), ('to_read', 'To Read'), ('watchlist', 'Watchlist')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('preview_link', models.URLField(blank=True)),
                ('read_link', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EBook',
        ),
    ]
