# Generated by Django 5.1.4 on 2025-04-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='google_book_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
